# Generated by Django 3.0.7 on 2020-11-04 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
    ]
